/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import designpatterns.config.PropertiesManager;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import org.scilab.forge.jlatexmath.TeXConstants;
import org.scilab.forge.jlatexmath.TeXFormula;
import org.scilab.forge.jlatexmath.TeXIcon;

/**
 *
 * @author bruno
 */
public class AboutEquationsForm extends javax.swing.JFrame {

    /**
     * Creates new form AboutFormulasForm
     */
    public AboutEquationsForm() {
        this.properties = PropertiesManager.getInstance().getProperties();
        initComponents();
        loadText();
        this.setLocationRelativeTo(null);
        this.setTitle(this.properties.getProperty("titleAbout"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelAbout = new javax.swing.JLabel();
        jPanelFormulas = new javax.swing.JPanel();
        jLabelSupport = new javax.swing.JLabel();
        jLabelConfidence = new javax.swing.JLabel();
        jLabelLift = new javax.swing.JLabel();
        jLabelConvition = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabelAbout.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabelAbout.setText("About Association Rules");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabelAbout)
                .addGap(133, 133, 133))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelAbout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelFormulas.setBorder(javax.swing.BorderFactory.createTitledBorder("Equations"));

        jLabelSupport.setText("jLabel1");

        jLabelConfidence.setText("jLabel2");

        jLabelLift.setText("jLabel3");

        jLabelConvition.setText("jLabel1");
        loadFormulas();

        javax.swing.GroupLayout jPanelFormulasLayout = new javax.swing.GroupLayout(jPanelFormulas);
        jPanelFormulas.setLayout(jPanelFormulasLayout);
        jPanelFormulasLayout.setHorizontalGroup(
            jPanelFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormulasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormulasLayout.createSequentialGroup()
                        .addComponent(jLabelSupport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelLift))
                    .addGroup(jPanelFormulasLayout.createSequentialGroup()
                        .addComponent(jLabelConfidence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelConvition)))
                .addContainerGap())
        );
        jPanelFormulasLayout.setVerticalGroup(
            jPanelFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormulasLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupport)
                    .addComponent(jLabelLift))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanelFormulasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfidence)
                    .addComponent(jLabelConvition))
                .addGap(25, 25, 25))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanelFormulas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelFormulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadFormulas(){
        String mathSupport = this.properties.getProperty("equation1");
        String mathConfidence = this.properties.getProperty("equation2");
        String mathLift = this.properties.getProperty("equation3");
        String mathConviction = this.properties.getProperty("equation4");
        
        TeXFormula formulaSupport = new TeXFormula(mathSupport);
        TeXFormula formulaConfidence = new TeXFormula(mathConfidence);
        TeXFormula formulaLift = new TeXFormula(mathLift);
        TeXFormula formulaConviction = new TeXFormula(mathConviction);
        
        TeXIcon iconSupport = formulaSupport.createTeXIcon(TeXConstants.STYLE_DISPLAY, 15);
        TeXIcon iconConfidence = formulaConfidence.createTeXIcon(TeXConstants.STYLE_DISPLAY, 15);
        TeXIcon iconLift = formulaLift.createTeXIcon(TeXConstants.STYLE_DISPLAY, 15);
        TeXIcon iconConviction = formulaConviction.createTeXIcon(TeXConstants.STYLE_DISPLAY, 15);
        
        BufferedImage bSup = new BufferedImage(iconSupport.getIconWidth(), iconSupport.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        BufferedImage bConf = new BufferedImage(iconConfidence.getIconWidth(), iconConfidence.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        BufferedImage bLift = new BufferedImage(iconLift.getIconWidth(), iconLift.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        BufferedImage bConv = new BufferedImage(iconConviction.getIconWidth(), iconConviction.getIconHeight(), BufferedImage.TYPE_4BYTE_ABGR);
        
        iconSupport.paintIcon(new JLabel(), bSup.getGraphics(), 0, 0);
        iconConfidence.paintIcon(new JLabel(), bConf.getGraphics(), 0, 0);
        iconLift.paintIcon(new JLabel(), bLift.getGraphics(), 0, 0);
        iconConviction.paintIcon(new JLabel(), bConv.getGraphics(), 0, 0);
        
        this.jLabelSupport.setIcon(iconSupport);
        this.jLabelConfidence.setIcon(iconConfidence);
        this.jLabelLift.setIcon(iconLift);
        this.jLabelConvition.setIcon(iconConviction);
    }
    
    private void loadText(){
        BufferedReader bufferedReader = null;
        String description = "";
        try {
            bufferedReader = new BufferedReader(new FileReader(getClass().getResource("../designpatterns/config/about_association_rules.txt").getFile()));
            int index = 0;
            while (bufferedReader.ready()) {
                description += bufferedReader.readLine();
                description = description.replace("\\n", "\n");
            }
            bufferedReader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                bufferedReader.close();
            } catch (IOException ex) {
                Logger.getLogger(AboutForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        this.jTextArea1.setText(description);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAbout;
    private javax.swing.JLabel jLabelConfidence;
    private javax.swing.JLabel jLabelConvition;
    private javax.swing.JLabel jLabelLift;
    private javax.swing.JLabel jLabelSupport;
    private javax.swing.JPanel jPanelFormulas;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private Properties properties;
}
